apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kubernetes
  description: 
    Kubernetes
  links:
    - title: Website
      url: https://kubernetes.io/
    - title: Documentation
      url: https://kubernetes.io/docs/home/
      icon: docs
  annotations:
    github.com/project-slug:  "PhoenixRedflash/kubernetes" 
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: "Group:Phoenix"
  lifecycle: experimental
